### ISSUE TITLE
User management add/ list template bug

### ISSUE THREAD

**Issue by VincentVW** [geex-arts/django-jet#175]
Dunno if this is just the demo, but here:

http://demo.jet.geex-arts.com/admin/auth/user/add/

you can add a password but no username. Submitting this results in a user with username None. 

Then when you go to http://demo.jet.geex-arts.com/admin/auth/user/ you get a 500 response.

**Comment by Ismael-VC** [comment]
I can reproduce this too.

**Comment by SalahAdDin** [comment]
@VincentVW, @Ismael-VC, Can you put here the error trace back please?

**Comment by Ismael-VC** [comment]
@SalahAdDin I can't provide a backtrace because this doesn't happen with my installation of Django 1.10.5

![image](https://cloud.githubusercontent.com/assets/4594825/23356061/1fed5f92-fc9e-11e6-893c-37b326b06826.png)

However the demo is actually missing this widget input field:

![image](https://cloud.githubusercontent.com/assets/4594825/23356116/506b8900-fc9e-11e6-97ae-5f6dab836971.png)

Which allows to save:

![image](https://cloud.githubusercontent.com/assets/4594825/23356154/6828c1f2-fc9e-11e6-8f76-a1b2e693a41a.png)

But since the demo is not running with `DEBUG = True`, there is no backtrace:

![image](https://cloud.githubusercontent.com/assets/4594825/23356296/eab38648-fc9e-11e6-8aff-8ad3ec061939.png)

**Comment by SalahAdDin** [comment]
@Ismael-VC Yes, but you can get a traceback from browser's debug console.
