### ISSUE TITLE
Regarding beta phase of this package

### ISSUE THREAD

**Issue by Ajeetlakhani** [geex-arts/django-jet#24]
I like this plugin and would like to use this in my product. I want to ask certain question regarding its beta phase .

1. What is the development status of this package?
2. There is no test written for this package. Is this package production ready?
3. How much compatible is it with various django versions ?

**Comment by f1nality** [comment]
1. This notice (Current version is still in beta phase...) is preserved since JET was published and not so actual at the moment. The only missing thing that doesn't allow us to make JET stable instead of beta is not full documentation. In the next few version documentation will be updated and project status will become stable.
2. In fact there are tests, but coverage is not so good (only 49% now). It will also increase in the next updates.
https://travis-ci.org/geex-arts/django-jet
https://coveralls.io/github/geex-arts/django-jet
These updated are going to be released within a month. But even now it can be used for production needs.
3. You can look into travis for this, compatible versions are Django 1.6-1.8

**Comment by Ajeetlakhani** [comment]
Thank you for your kind response. I am looking forward to use it. :)

**Comment by belugame** [comment]
@f1nality Could you tell me if django-jet works fine with a custom admin site? I have one se tup and all models show up in the main part of the template but the left jet sidebar is empty now.
![2016-01-30-210812_2806x900_scrot](https://cloud.githubusercontent.com/assets/16137830/12698145/af770e40-c795-11e5-91ac-505919006d0c.png)
